### ISSUE TITLE
Error in Dockerfile

### ISSUE THREAD

**Issue by schmandr** [sogis/docker-mapcache#1]
Line

https://github.com/sogis/docker-mapcache/blob/225d62b50515c99527e73db0cb726e91b074ddea/Dockerfile#L44

is not working:

```
Step 20/26 : ADD dockerlog-run.sh /etc/service/dockerlog/run
ADD failed: stat /var/lib/docker/tmp/docker-builder483136800/dockerlog-run.sh: no such file or directory
```

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/docker-mapcache/commit/32b53a0207b7a9ce78f6d28937510b550c6fb892

Hab das Docker-Log-Zeugs gelöscht. War etwas mit QGIS-Server Logfiles. Daher hoffe ich, dass es für Mapcache nicht wirklich relevant ist. GetCapabilities ging bei mir.

Wie das funktionieren konnte...? Wahrscheinlich nicht alles committed.
